### ISSUE TITLE
red light while breaking block

### ISSUE THREAD

**Issue by GyomeiHimejima9906** [Despatra/Phoxel#21]
**Describe the bug**
the mountain on my world don't used to calculate sun shadow

**Steps to Reproduce**
1. open a survival wold
2. try to breake a stone
3. you will see a red light while breaking block

**Screenshots**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/4732426c-c0cb-4360-bdb3-d4fda317d73a">

**Comment by Despatra** [comment]
Hello, I haven't given any notice so far to you, so that you are informed I think I might know the issue, which I think I fixed in the more recent updates. If you could let me know if this is still an ongoing issue I would appreciate it! Hope to hear back from you soon and sorry for taking so long to reply.
If I do not get a response within 2 weeks I will close this issue due to my belief I have fixed it and no confirmation otherwise.
Thank you for youre time!
